# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleadores',
            fields=[
                ('RNC', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('FechaConst', models.DateField()),
                ('Direccion', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=50)),
                ('Clave', models.CharField(max_length=75)),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_Empl',
            fields=[
                ('Cod_OfertaTrbj', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_P', models.IntegerField()),
                ('Puesto', models.CharField(max_length=50)),
                ('A_Experiencia', models.IntegerField()),
                ('Horario_Trbj', models.CharField(max_length=25)),
                ('Salario', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Estado', models.CharField(max_length=1)),
                ('Empleadores_RNC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Empleadores')),
            ],
        ),
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('Entrada', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=100)),
                ('Sexo', models.CharField(max_length=1)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Email', models.EmailField(max_length=50)),
                ('Clave', models.CharField(max_length=75)),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('Cod_TipoEmpr', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=5)),
                ('Descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='empleadores',
            name='FormaJurd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.TipoEmpresa'),
        ),
    ]
