# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('Cod_Carr', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleadores',
            fields=[
                ('Nombre', models.CharField(max_length=50)),
                ('FechaConst', models.DateField()),
                ('RNC', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=50)),
                ('Clave', models.CharField(max_length=75)),
                ('Clave2', models.CharField(max_length=75)),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('Cod_Gen', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Sigla', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadesCarr',
            fields=[
                ('Cod_Habld', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Cod_Carr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Carreras')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadesEstd',
            fields=[
                ('Cod_Habld', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstEstd',
            fields=[
                ('Cod_InstEstd', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_Empl',
            fields=[
                ('Cod_OfertaTrbj', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_P', models.IntegerField()),
                ('Puesto', models.CharField(max_length=50)),
                ('A_Experiencia', models.IntegerField()),
                ('Horario_Trbj', models.CharField(max_length=25)),
                ('Salario', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Estado', models.CharField(max_length=1)),
                ('Empleadores_RNC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Empleadores')),
            ],
        ),
        migrations.CreateModel(
            name='OtrosEstd',
            fields=[
                ('Cod_Estd', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Cod_InstEstd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.InstEstd')),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('Cod_Pais', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('Cod_Provincia', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=100)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Email', models.EmailField(max_length=50)),
                ('Clave', models.CharField(max_length=75)),
                ('Clave2', models.CharField(max_length=75)),
                ('Estado', models.CharField(max_length=1)),
                ('Sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('Cod_TipoEmpr', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=10)),
                ('Descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('Cod_Univ', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='habilidadesestd',
            name='Cod_Estd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.OtrosEstd'),
        ),
        migrations.AddField(
            model_name='empleadores',
            name='Direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Provincias'),
        ),
        migrations.AddField(
            model_name='empleadores',
            name='FormaJurd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.TipoEmpresa'),
        ),
        migrations.AddField(
            model_name='carreras',
            name='InstEstd',
            field=models.ManyToManyField(to='App_Get_a_Job.InstEstd'),
        ),
    ]
