# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Get_a_Job', '0002_delete_pruebas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('Cod_Gen', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Sigla', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Genero'),
        ),
    ]
