# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Get_a_Job', '0003_auto_20180731_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadores',
            name='Clave2',
            field=models.CharField(default=123456, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='Clave2',
            field=models.CharField(default='getajob123', max_length=75),
            preserve_default=False,
        ),
    ]
