# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Get_a_Job', '0005_auto_20180731_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='InstEstd',
        ),
        migrations.AddField(
            model_name='carreras',
            name='InstEstd',
            field=models.ManyToManyField(to='App_Get_a_Job.InstEstd'),
        ),
    ]
