# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Get_a_Job', '0006_auto_20180731_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoempresa',
            name='Nombre',
            field=models.CharField(max_length=10),
        ),
    ]
