# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Get_a_Job', '0007_auto_20180731_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadores',
            name='Direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Get_a_Job.Provincias'),
        ),
    ]
