# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Get_a_Job', '0008_auto_20180731_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('Cod_Pais', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='Carrera_P',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='Cedula_Solct',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='Otro_Estd',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
